# Generated by Django 5.2.6 on 2025-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Character's name (e.g., 'Goblin Scout')",
                        max_length=100,
                    ),
                ),
                (
                    "initiative",
                    models.IntegerField(
                        default=0, help_text="Initiative roll (higher goes first)"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Order position (GM adjustable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "-initiative"],
            },
        ),
    ]
