# Generated by Django 5.2.6 on 2025-09-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("initiative_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={
                "ordering": ["position", "-initiative"],
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
            },
        ),
    ]
