# Generated by Django 5.2.6 on 2025-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiative_tracker", "0002_alter_character_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="initiative",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Initiative roll (higher goes first)",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Character's name (e.g., 'Goblin Scout')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Order position (GM adjustable)"
            ),
        ),
    ]
