name: PR Linting and Quality Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev

    - name: Install Python dependencies with Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev

    - name: Check Django setup
      run: |
        pipenv run python manage.py check
        pipenv run python manage.py makemigrations --check --dry-run

    - name: Run linting with flake8
      run: |
        pipenv run flake8 core/ initiative_tracker/ tabletop_utils/ manage.py

    - name: Check code formatting with black
      run: |
        pipenv run black --check .

    - name: Check import sorting with isort
      run: |
        pipenv run isort --check-only .

    - name: Run type checking with mypy
      run: |
        pipenv run mypy core/ initiative_tracker/ tabletop_utils/ --ignore-missing-imports

    - name: Run Django tests
      run: |
        pipenv run python manage.py test